version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/foodTruck
    ports:
      - "9000:9000"
    working_dir: /var/www/foodTruck
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/foodTruck
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data: {}

